/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmstu.drivers.manager.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import com.bmstu.drivers.manager.core.model.Driver;
import com.bmstu.drivers.manager.core.model.DriverModel;
import com.bmstu.drivers.manager.core.model.DriverSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Driver service. Represents a row in the &quot;com.bmstu.drivers.manager.core_Driver&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DriverModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DriverImpl}.
 * </p>
 *
 * @author Romanova
 * @see DriverImpl
 * @see Driver
 * @see DriverModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DriverModelImpl extends BaseModelImpl<Driver>
	implements DriverModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a driver model instance should use the {@link Driver} interface instead.
	 */
	public static final String TABLE_NAME = "service_builder_Driver";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "driverId", Types.BIGINT },
			{ "driverName", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("driverId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("driverName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table service_builder_Driver (uuid_ VARCHAR(75) null,driverId LONG not null primary key,driverName VARCHAR(75) null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table service_builder_Driver";
	public static final String ORDER_BY_JPQL = " ORDER BY driver.driverId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY service_builder_Driver.driverId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.bmstu.drivers.manager.core.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.bmstu.drivers.manager.core.model.Driver"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.bmstu.drivers.manager.core.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.bmstu.drivers.manager.core.model.Driver"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.bmstu.drivers.manager.core.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.bmstu.drivers.manager.core.model.Driver"),
			true);
	public static final long DRIVERID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Driver toModel(DriverSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Driver model = new DriverImpl();

		model.setUuid(soapModel.getUuid());
		model.setDriverId(soapModel.getDriverId());
		model.setDriverName(soapModel.getDriverName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Driver> toModels(DriverSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Driver> models = new ArrayList<Driver>(soapModels.length);

		for (DriverSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.bmstu.drivers.manager.core.service.util.ServiceProps.get(
				"lock.expiration.time.com.bmstu.drivers.manager.core.model.Driver"));

	public DriverModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _driverId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDriverId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _driverId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Driver.class;
	}

	@Override
	public String getModelClassName() {
		return Driver.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("driverId", getDriverId());
		attributes.put("driverName", getDriverName());
		attributes.put("description", getDescription());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long driverId = (Long)attributes.get("driverId");

		if (driverId != null) {
			setDriverId(driverId);
		}

		String driverName = (String)attributes.get("driverName");

		if (driverName != null) {
			setDriverName(driverName);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDriverId() {
		return _driverId;
	}

	@Override
	public void setDriverId(long driverId) {
		_columnBitmask |= DRIVERID_COLUMN_BITMASK;

		if (!_setOriginalDriverId) {
			_setOriginalDriverId = true;

			_originalDriverId = _driverId;
		}

		_driverId = driverId;
	}

	public long getOriginalDriverId() {
		return _originalDriverId;
	}

	@JSON
	@Override
	public String getDriverName() {
		if (_driverName == null) {
			return StringPool.BLANK;
		}
		else {
			return _driverName;
		}
	}

	@Override
	public void setDriverName(String driverName) {
		_driverName = driverName;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Driver.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Driver toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Driver)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DriverImpl driverImpl = new DriverImpl();

		driverImpl.setUuid(getUuid());
		driverImpl.setDriverId(getDriverId());
		driverImpl.setDriverName(getDriverName());
		driverImpl.setDescription(getDescription());

		driverImpl.resetOriginalValues();

		return driverImpl;
	}

	@Override
	public int compareTo(Driver driver) {
		long primaryKey = driver.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Driver)) {
			return false;
		}

		Driver driver = (Driver)obj;

		long primaryKey = driver.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DriverModelImpl driverModelImpl = this;

		driverModelImpl._originalUuid = driverModelImpl._uuid;

		driverModelImpl._originalDriverId = driverModelImpl._driverId;

		driverModelImpl._setOriginalDriverId = false;

		driverModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Driver> toCacheModel() {
		DriverCacheModel driverCacheModel = new DriverCacheModel();

		driverCacheModel.uuid = getUuid();

		String uuid = driverCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			driverCacheModel.uuid = null;
		}

		driverCacheModel.driverId = getDriverId();

		driverCacheModel.driverName = getDriverName();

		String driverName = driverCacheModel.driverName;

		if ((driverName != null) && (driverName.length() == 0)) {
			driverCacheModel.driverName = null;
		}

		driverCacheModel.description = getDescription();

		String description = driverCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			driverCacheModel.description = null;
		}

		return driverCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", driverId=");
		sb.append(getDriverId());
		sb.append(", driverName=");
		sb.append(getDriverName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.bmstu.drivers.manager.core.model.Driver");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>driverId</column-name><column-value><![CDATA[");
		sb.append(getDriverId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>driverName</column-name><column-value><![CDATA[");
		sb.append(getDriverName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Driver.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Driver.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _driverId;
	private long _originalDriverId;
	private boolean _setOriginalDriverId;
	private String _driverName;
	private String _description;
	private long _columnBitmask;
	private Driver _escapedModel;
}